import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { SessionProvider } from "@/components/providers/session-provider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { getUserPreferences } from "@/lib/actions/preferences";
import { PreferencesProvider } from '@/providers/preferences-provider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  const preferences = session?.user ? await getUserPreferences() : null;

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <SessionProvider session={session}>
          <PreferencesProvider
            defaultTheme={preferences?.theme || "system"}
            defaultOrganizationId={preferences?.defaultOrganizationId}
          >
            {children}
          </PreferencesProvider>
        </SessionProvider>
      </body>
    </html>
  );
}